version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(filename)s:%(lineno)d | %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    encoding: utf8

loggers:
  # Default logger
  '':
    level: INFO
    handlers: [ console, info_file_handler, error_file_handler ]
    propagate: false

  # NASA APOD extraction job logger
  apod_extractor:
    level: DEBUG
    handlers: [ console, info_file_handler, error_file_handler ]
    propagate: false

  # NASA NEO extraction job logger
  neo_extractor:
    level: DEBUG
    handlers: [ console, info_file_handler, error_file_handler ]
    propagate: false

  # NASA MARS extraction job logger
  mars_extractor:
    level: DEBUG
    handlers: [ console, info_file_handler, error_file_handler ]
    propagate: false